// <auto-generated />
using ASPCoreFormSelectDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPCoreFormSelectDemo.Migrations
{
    [DbContext(typeof(PeopleDataContext))]
    partial class PeopleDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASPCoreFormSelectDemo.Models.CodeBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Gray"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Blue"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Green"
                        });
                });

            modelBuilder.Entity("ASPCoreFormSelectDemo.Models.Human", b =>
                {
                    b.Property<int>("HumanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HumanId"), 1L, 1);

                    b.Property<int>("EyeColorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShoeSize")
                        .HasColumnType("int");

                    b.HasKey("HumanId");

                    b.HasIndex("EyeColorId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ASPCoreFormSelectDemo.Models.Human", b =>
                {
                    b.HasOne("ASPCoreFormSelectDemo.Models.CodeBook", "EyeColor")
                        .WithMany()
                        .HasForeignKey("EyeColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EyeColor");
                });
#pragma warning restore 612, 618
        }
    }
}
